<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateTickersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tickers', function (Blueprint $table) {
            $table->id();
            $table->string('nama');
            $table->string('code');
            $table->timestamps();
        });
        DB::unprepared("INSERT INTO tickers (nama, code) VALUES
        ('Astra Agro Lestari Tbk.','AALI'),
        ('Mahaka Media Tbk.','ABBA'),
        ('Asuransi Bina Dana Arta Tbk.','ABDA'),
        ('ABM Investama Tbk.	','ABMM'),
        ('Ace Hardware Indonesia Tbk.	','ACES'),
        ('Acset Indonusa Tbk.	','ACST'),
        ('Akasha Wira International Tbk.	','ADES'),
        ('Adhi Karya (Persero) Tbk.	','ADHI'),
        ('Adira Dinamika Multi Finance T	','ADMF'),
        ('Polychem Indonesia Tbk	','ADMG'),
        ('Adaro Energy Tbk.	','ADRO'),
        ('Asia Sejahtera Mina Tbk.	','AGAR'),
        ('Aneka Gas Industri Tbk.	','AGII'),
        ('Bank Rakyat Indonesia Agroniag	','AGRO'),
        ('Bank IBK Indonesia Tbk.	','AGRS'),
        ('Asuransi Harta Aman Pratama Tb	','AHAP'),
        ('Akbar Indo Makmur Stimec Tbk	','AIMS'),
        ('FKS Food Sejahtera Tbk.	','AISA'),
        ('Anugerah Kagum Karya Utama Tbk	','AKKU'),
        ('Argha Karya Prima Industry Tbk	','AKPI'),
        ('AKR Corporindo Tbk.	','AKRA'),
        ('Maming Enam Sembilan Mineral T	','AKSI'),
        ('Alkindo Naratama Tbk.	','ALDO'),
        ('Alakasa Industrindo Tbk	','ALKA'),
        ('Alumindo Light Metal Industry	','ALMI'),
        ('Tri Banyan Tirta Tbk.	','ALTO'),
        ('Asuransi Multi Artha Guna Tbk.	','AMAG'),
        ('Makmur Berkah Amanda Tbk.	','AMAN'),
        ('Bank Amar Indonesia Tbk.	','AMAR'),
        ('Asahimas Flat Glass Tbk.	','AMFG'),
        ('Ateliers Mecaniques D Indonesi	','AMIN'),
        ('Ashmore Asset Management Indon	','AMOR'),
        ('Sumber Alfaria Trijaya Tbk.	','AMRT'),
        ('Andira Agro Tbk.	','ANDI'),
        ('Austindo Nusantara Jaya Tbk.	','ANJT'),
        ('Aneka Tambang Tbk.	','ANTM'),
        ('Apexindo Pratama Duta Tbk.	','APEX'),
        ('Pacific Strategic Financial Tb	','APIC'),
        ('Arita Prima Indonesia Tbk.	','APII'),
        ('Asiaplast Industries Tbk.	','APLI'),
        ('Agung Podomoro Land Tbk.	','APLN'),
        ('Archi Indonesia Tbk.	','ARCI'),
        ('Argo Pantes Tbk	','ARGO'),
        ('Atlas Resources Tbk.	','ARII'),
        ('Arkha Jayanti Persada Tbk.	','ARKA'),
        ('Armidian Karyatama Tbk.	','ARMY'),
        ('Arwana Citramulia Tbk.	','ARNA'),
        ('Arthavest Tbk	','ARTA'),
        ('Ratu Prabu Energi Tbk	','ARTI'),
        ('Bank Jago Tbk.	','ARTO'),
        ('Asuransi Bintang Tbk.	','ASBI'),
        ('Asuransi Dayin Mitra Tbk.	','ASDM'),
        ('Astra Graphia Tbk.	','ASGR'),
        ('Astra International Tbk.	','ASII'),
        ('Asuransi Jasa Tania Tbk.	','ASJT'),
        ('Asuransi Maximus Graha Persada	','ASMI'),
        ('Andalan Sakti Primaindo Tbk.	','ASPI'),
        ('Alam Sutera Realty Tbk.	','ASRI'),
        ('Asuransi Ramayana Tbk.	','ASRM'),
        ('Adi Sarana Armada Tbk.	','ASSA'),
        ('Trimitra Prawara Goldland Tbk.	','ATAP'),
        ('Anabatic Technologies Tbk.	','ATIC'),
        ('Astra Otoparts Tbk.	','AUTO'),
        ('Agro Yasa Lestari Tbk.','AYLS'),
        ('Bank MNC Internasional Tbk.	','BABP'),
        ('Bank Capital Indonesia Tbk.	','BACA'),
        ('Saranacentral Bajatama Tbk.	','BAJA'),
        ('Bali Towerindo Sentra Tbk.	','BALI'),
        ('Bank Aladin Syariah Tbk.	','BANK'),
        ('Bekasi Asri Pemula Tbk.	','BAPA'),
        ('Bhakti Agung Propertindo Tbk.	','BAPI'),
        ('Sepatu Bata Tbk.	','BATA'),
        ('Bayu Buana Tbk	','BAYU'),
        ('Bank Central Asia Tbk.	','BBCA'),
        ('Allo Bank Indonesia Tbk.	','BBHI'),
        ('Bank KB Bukopin Tbk.	','BBKP'),
        ('Buana Finance Tbk.	','BBLD'),
        ('Bank Mestika Dharma Tbk.	','BBMD'),
        ('Bank Negara Indonesia (Persero	','BBNI'),
        ('Bank Rakyat Indonesia (Persero	','BBRI'),
        ('Pelayaran Nasional Bina Buana	','BBRM'),
        ('Bank Bisnis Internasional Tbk.	','BBSI'),
        ('Bumi Benowo Sukses Sejahtera T	','BBSS'),
        ('Bank Tabungan Negara (Persero)	','BBTN'),
        ('Bank Neo Commerce Tbk.	','BBYB'),
        ('MNC Kapital Indonesia Tbk.	','BCAP'),
        ('Bank JTrust Indonesia Tbk.	','BCIC'),
        ('Bumi Citra Permai Tbk.	','BCIP	'),
        ('Bank Danamon Indonesia Tbk.	.','BDMN'),
        ('Berkah Beton Sadaya Tbk.	','BEBS'),
        ('Estika Tata Tiara Tbk.','BEEF'),
        ('Bank Pembangunan Daerah Banten','BEKS'),
        ('Trisula Textile Industries Tbk','BELL'),
        ('Batulicin Nusantara Maritim Tb','BESS'),
        ('Bekasi Fajar Industrial Estate','BEST'),
        ('BFI Finance Indonesia Tbk.','BFIN'),
        ('Bank Ganesha Tbk.	','BGTG'),
        ('Bhakti Multi Artha Tbk.','BHAT'),
        ('MNC Investama Tbk.','BHIT'),
        ('Binakarya Jaya Abadi Tbk.	','BIKA'),
        ('Primarindo Asia Infrastructure	','BIMA'),
        ('Bank Ina Perdana Tbk.	','BINA'),
        ('Astrindo Nusantara Infrastrukt	','BIPI'),
        ('Bhuwanatala Indah Permai Tbk.	','BIPP'),
        ('Blue Bird Tbk.	','BIRD'),
        ('BISI International Tbk.	','BISI'),
        ('Bank Pembangunan Daerah Jawa B	','BJBR'),
        ('Bank Pembangunan Daerah Jawa T	','BJTM'),
        ('Bukit Darmo Property Tbk	','BKDP'),
        ('Sentul City Tbk.	','BKSL'),
        ('Bank QNB Indonesia Tbk.	','BKSW'),
        ('Berlian Laju Tanker Tbk	','BLTA'),
        ('Graha Layar Prima Tbk.	','BLTZ'),
        ('Berkah Prima Perkasa Tbk.	','BLUE'),
        ('Bank Maspion Indonesia Tbk.	','BMAS'),
        ('Bundamedik Tbk.	','BMHS'),
        ('Bank Mandiri (Persero) Tbk.	','BMRI'),
        ('Bintang Mitra Semestaraya Tbk	','BMSR'),
        ('Global Mediacom Tbk.	','BMTR'),
        ('Bank Bumi Arta Tbk.	','BNBA'),
        ('Bakrie & Brothers Tbk	','BNBR'),
        ('Bank CIMB Niaga Tbk.	','BNGA'),
        ('Bank Maybank Indonesia Tbk.	','BNII'),
        ('Bank Permata Tbk.	','BNLI'),
        ('Bintang Oto Global Tbk.	','BOGA'),
        ('Bali Bintang Sejahtera Tbk.	','BOLA'),
        ('Garuda Metalindo Tbk.	','BOLT'),
        ('Borneo Olah Sarana Sukses Tbk.	','BOSS'),
        ('Batavia Prosperindo Finance Tb	','BPFI'),
        ('Batavia Prosperindo Internasio	','BPII'),
        ('Batavia Prosperindo Trans Tbk.	','BPTR'),
        ('Indo Kordsa Tbk.	','BRAM'),
        ('Bank Syariah Indonesia Tbk.	','BRIS'),
        ('Bumi Resources Minerals Tbk.	','BRMS'),
        ('Berlina Tbk.	','BRNA'),
        ('Barito Pacific Tbk.	','BRPT'),
        ('Bumi Serpong Damai Tbk.	','BSDE'),
        ('Bank Sinarmas Tbk.	','BSIM'),
        ('Baramulti Suksessarana Tbk.	','BSSR'),
        ('Bank Of India Indonesia Tbk.	','BSWD'),
        ('Bumi Teknokultura Unggul Tbk	','BTEK'),
        ('Bakrie Telecom Tbk.	','BTEL'),
        ('Betonjaya Manunggal Tbk.	','BTON'),
        ('Bank BTPN Tbk.	','BTPN'),
        ('Bank BTPN Syariah Tbk.	','BTPS'),
        ('Budi Starch & Sweetener Tbk.	','BUDI'),
        ('Bukalapak.com Tbk.	','BUKA'),
        ('Bukaka Teknik Utama Tbk.	','BUKK'),
        ('Buana Lintas Lautan Tbk.	','BULL'),
        ('Bumi Resources Tbk.	','BUMI'),
        ('Bukit Uluwatu Villa Tbk.	','BUVA'),
        ('Bank Victoria International Tb	','BVIC'),
        ('Eagle High Plantations Tbk.	','BWPT'),
        ('Bayan Resources Tbk.	','BYAN'),
        ('Cahayaputra Asa Keramik Tbk.	','CAKK'),
        ('Campina Ice Cream Industry Tbk	','CAMP'),
        ('Capitol Nusantara Indonesia Tb	','CANI'),
        ('Metro Healthcare Indonesia Tbk	','CARE'),
        ('Industri dan Perdagangan Bintr	','CARS'),
        ('Capital Financial Indonesia Tb	','CASA'),
        ('Cashlez Worldwide Indonesia Tb	','CASH'),
        ('Cardig Aero Services Tbk.	','CASS'),
        ('Cahaya Bintang Medan Tbk.	','CBMF'),
        ('Communication Cable Systems In	','CCSI'),
        ('Wilmar Cahaya Indonesia Tbk.	','CEKA'),
        ('Centratama Telekomunikasi Indo	','CENT'),
        ('Clipan Finance Indonesia Tbk.	','CFIN'),
        ('Chitose Internasional Tbk.	','CINT'),
        ('Cita Mineral Investindo Tbk.	','CITA'),
        ('Natura City Developments Tbk.	','CITY'),
        ('Citra Putra Realty Tbk.	','CLAY'),
        ('Sariguna Primatirta Tbk.	','CLEO'),
        ('Colorpak Indonesia Tbk.	','CLPI'),
        ('Citra Marga Nusaphala Persada	','CMNP'),
        ('Cemindo Gemilang Tbk.	','CMNT'),
        ('AirAsia Indonesia Tbk.	','CMPP'),
        ('Exploitasi Energi Indonesia Tb	','CNKO'),
        ('Century Textile Industry Tbk.	','CNTX'),
        ('Wahana Interfood Nusantara Tbk	','COCO'),
        ('Cowell Development Tbk.	','COWL'),
        ('Charoen Pokphand Indonesia Tbk	','CPIN'),
        ('Capri Nusa Satu Properti Tbk.	','CPRI'),
        ('Central Proteina Prima Tbk.	','CPRO'),
        ('Catur Sentosa Adiprana Tbk.	','CSAP'),
        ('Cahayasakti Investindo Sukses	','CSIS'),
        ('Cipta Selera Murni Tbk.	','CSMI'),
        ('Cisadane Sawit Raya Tbk.	','CSRA'),
        ('Citra Tubindo Tbk.	','CTBN'),
        ('Ciputra Development Tbk.	','CTRA'),
        ('Citatah Tbk.	','CTTH'),
        ('Diamond Citra Propertindo Tbk.	','DADA'),
        ('Duta Anggada Realty Tbk.	','DART'),
        ('Duta Intidaya Tbk.	','DAYA'),
        ('DCI Indonesia Tbk.	','DCII'),
        ('Dewata Freightinternational Tb	','DEAL'),
        ('Danasupra Erapacific Tbk.	','DEFI'),
        ('Darma Henwa Tbk	','DEWA'),
        ('Dafam Property Indonesia Tbk.	','DFAM'),
        ('Nusa Konstruksi Enjiniring Tbk	','DGIK'),
        ('Diagnos Laboratorium Utama Tbk	','DGNS'),
        ;");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tickers');
    }
}
